[_]
schema-version = "0.2"

[project]
name = "function"
description = ""
version = "0.1.0"
requires-python = ">=3.9"
readme = "README.md"
license = "MIT"
dependencies = [
  "httpx",
  "cloudevents",
  "pytest",
  "pytest-asyncio",
  "PyYAML",
  "ruff>=0.14.10",
]
authors = [
  { name="Raito Denki", email="arichichinoraitodenki@gmail.com"},
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"

#[tool.uv.workspace]
#members = [
#    "function",
#]
